name: Deploy to EC2

on:
  push:
    branches:
      - main  # or 'master' based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.48.57.137 >> ~/.ssh/known_hosts

    - name: Deploy to EC2 and start Gradio app
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@13.48.57.137 << 'EOF'
          cd ~/CloudLabs-Snowflake
          git pull origin main
          nohup python3 app.py > app.log 2>&1 &
        EOF
